//! Documentation generator: IR + Display annotations -> markdown.
//! Dogfoods the annotation layer — everything shown here comes from
//! the description itself, nothing is hand-maintained.

use crate::ir::pb;
use anyhow::{Context, Result};
use std::fmt::Write;

/// If `e` is the frontends' byte-length sugar `expr * 8` (either
/// operand order), the byte-denominated inner expression. Purely
/// presentational — semantics always use the bit length.
fn as_byte_len(e: &pb::Expr) -> Option<&pb::Expr> {
    let Some(pb::expr::Kind::Bin(b)) = e.kind.as_ref() else {
        return None;
    };
    if pb::BinOpKind::try_from(b.op) != Ok(pb::BinOpKind::Mul) {
        return None;
    }
    let is_eight = |x: &pb::Expr| matches!(x.kind.as_ref(), Some(pb::expr::Kind::Constant(8)));
    match (b.lhs.as_deref(), b.rhs.as_deref()) {
        (Some(l), Some(r)) if is_eight(r) => Some(l),
        (Some(l), Some(r)) if is_eight(l) => Some(r),
        _ => None,
    }
}

pub fn generate_markdown(ir: &crate::ir::ValidatedIr) -> Result<String> {
    let parser = ir
        .parser
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("ir has no parser"))?;
    let mut out = String::new();
    let w = &mut out;
    writeln!(w, "# `{}`", parser.name)?;
    writeln!(w)?;
    writeln!(
        w,
        "Generated by `pakeles doc` from IR version {}. Parse depth bound: {}.",
        ir.ir_version, parser.max_depth
    )?;
    if let Some(doc) = parser.annotations.get("doc") {
        writeln!(w)?;
        writeln!(w, "{doc}")?;
    }

    for ht in &parser.header_types {
        writeln!(w)?;
        writeln!(w, "## Header `{}`", ht.name)?;
        writeln!(w)?;
        writeln!(w, "| Field | Bits | Format | Name | Labels | Notes |")?;
        writeln!(w, "|---|---|---|---|---|---|")?;
        for f in &ht.fields {
            let width = match f.width.as_ref().and_then(|x| x.width.as_ref()) {
                Some(pb::field_width::Width::Bits(n)) => n.to_string(),
                // Present the frontends' ×8 sugar back in bytes — the
                // unit the wire format was authored in; a genuinely
                // bit-granular length renders in bits.
                Some(pb::field_width::Width::BitLen(e)) => match as_byte_len(e) {
                    Some(bytes) => format!("`{}` bytes", crate::viz::expr_text(bytes)),
                    None => format!("`{}` bits", crate::viz::expr_text(e)),
                },
                None => "?".into(),
            };
            let d = f.display.clone().unwrap_or_default();
            let format = match pb::DisplayFormat::try_from(d.format).unwrap_or_default() {
                pb::DisplayFormat::Dec => "dec",
                pb::DisplayFormat::Hex => "hex",
                pb::DisplayFormat::Bin => "bin",
                pb::DisplayFormat::Ipv4 => "IPv4",
                pb::DisplayFormat::Ipv6 => "IPv6",
                pb::DisplayFormat::Ether => "MAC",
                pb::DisplayFormat::Unspecified => "",
            };
            let labels = d
                .value_labels
                .iter()
                .map(|vl| format!("{}={}", vl.value, vl.label))
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(
                w,
                "| `{}` | {} | {} | {} | {} | {} |",
                f.name, width, format, d.name, labels, d.doc
            )?;
        }
    }

    if !parser.metadata.is_empty() {
        writeln!(w)?;
        writeln!(w, "## Metadata")?;
        writeln!(w)?;
        writeln!(w, "| Field | Bits | Init | Format | Name | Notes |")?;
        writeln!(w, "|---|---|---|---|---|---|")?;
        for md in &parser.metadata {
            let d = md.display.clone().unwrap_or_default();
            let format = match pb::DisplayFormat::try_from(d.format).unwrap_or_default() {
                pb::DisplayFormat::Dec => "dec",
                pb::DisplayFormat::Hex => "hex",
                pb::DisplayFormat::Bin => "bin",
                pb::DisplayFormat::Ipv4 => "IPv4",
                pb::DisplayFormat::Ipv6 => "IPv6",
                pb::DisplayFormat::Ether => "MAC",
                pb::DisplayFormat::Unspecified => "",
            };
            writeln!(
                w,
                "| `{}` | {} | {} | {} | {} | {} |",
                md.name, md.bits, md.init, format, d.name, d.doc
            )?;
        }
    }

    writeln!(w)?;
    writeln!(w, "## Parse graph")?;
    writeln!(w)?;
    writeln!(w, "Start state: `{}`.", parser.start_state)?;
    writeln!(w)?;
    for s in &parser.states {
        let extracts = s
            .extracts
            .iter()
            .map(|e| {
                let inst = if e.instance.is_empty() {
                    e.header_type.clone()
                } else {
                    e.instance.clone()
                };
                if e.lookahead {
                    format!("{inst} (lookahead)")
                } else {
                    inst
                }
            })
            .collect::<Vec<_>>()
            .join(", ");
        write!(w, "- **`{}`**", s.name)?;
        if !extracts.is_empty() {
            write!(w, " — extracts {extracts}")?;
        }
        for a in &s.assigns {
            let val = crate::viz::expr_text(a.value.as_ref().context("assign without value")?);
            write!(w, "; sets meta.{} = {}", a.metadata, val)?;
        }
        match s.transition.as_ref().and_then(|t| t.kind.as_ref()) {
            Some(pb::transition::Kind::Direct(t)) => {
                writeln!(w, "; then {}", target_text(t))?;
            }
            Some(pb::transition::Kind::Select(sel)) => {
                writeln!(w, "; selects on {}:", keys_text(&sel.keys))?;
                for arm in &sel.arms {
                    let entries = arm
                        .entries
                        .iter()
                        .zip(&sel.keys)
                        .map(|(e, k)| crate::viz::entry_text(k, e))
                        .collect::<Vec<_>>()
                        .join(" && ");
                    let next = arm.next.as_ref().map(target_text).unwrap_or_default();
                    writeln!(w, "  - {entries} → {next}")?;
                }
                if let Some(t) = &sel.default_target {
                    writeln!(w, "  - otherwise → {}", target_text(t))?;
                }
            }
            None => writeln!(w)?,
        }
        if let Some(doc) = s.annotations.get("doc") {
            for line in doc.lines() {
                if line.is_empty() {
                    writeln!(w, "  >")?;
                } else {
                    writeln!(w, "  > {line}")?;
                }
            }
        }
    }
    Ok(out)
}

fn keys_text(keys: &[pb::Expr]) -> String {
    keys.iter()
        .map(|k| format!("`{}`", crate::viz::expr_text(k)))
        .collect::<Vec<_>>()
        .join(", ")
}

fn target_text(t: &pb::Target) -> String {
    match t.kind.as_ref() {
        Some(pb::target::Kind::State(s)) => format!("`{s}`"),
        Some(pb::target::Kind::Accept(_)) => "**accept**".into(),
        Some(pb::target::Kind::Reject(r)) => {
            let info = r.annotations.get("severity").map(String::as_str) == Some("info");
            if info {
                format!("payload boundary (*{}*)", r.reason)
            } else {
                format!("**reject** (*{}*)", r.reason)
            }
        }
        None => "?".into(),
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn metadata_doc_section() {
        let ir = crate::builder::meta_loop(); // shared test IR from Task 2
        let md = super::generate_markdown(&ir).unwrap();
        assert!(md.contains("## Metadata"), "{md}");
        assert!(md.contains("sets meta.acc"), "{md}");
    }

    // The committed-doc equality guard lives in tests/synthetic_gallery.rs
    // (pakeles-testkit's committed_artifacts_current); this checks shape.
    #[test]
    fn doc_has_field_tables_and_payload_note() {
        let md = super::generate_markdown(&crate::fixtures::eth_ipvx_l4()).unwrap();
        assert!(md.contains("| `ttl` | 8 | dec | Time to Live |"));
        assert!(md.contains("payload boundary"));
    }

    #[test]
    fn doc_annotations_render_as_prose() {
        let mut ir = crate::builder::meta_loop().into_inner();
        let parser = ir.parser.as_mut().unwrap();
        parser
            .annotations
            .insert("doc".into(), "Parser-level prose.".into());
        parser.states[0]
            .annotations
            .insert("doc".into(), "First line.\n\nSecond line.".into());
        let ir = crate::ir::ValidatedIr::new(ir).unwrap();
        let md = super::generate_markdown(&ir).unwrap();
        assert!(md.contains("\nParser-level prose.\n"), "{md}");
        assert!(
            md.contains("  > First line.\n  >\n  > Second line.\n"),
            "{md}"
        );
    }
}
