"""Generate the observation wrapper for the vendored DASH BMv2 parser,
making the parse observable on simple_switch.

Unlike the sai factory (which patches a copy of a complete program),
the vendored `dash_parser.p4` is a bare parser + deparser, so nothing
is patched at all: this script emits a minimal v1model program
(`build/main.p4`) that `#include`s the UNMODIFIED vendored parser, runs
it as a sub-parser, and emits ONLY a `pk_verdict` header per packet — a
header-validity bitmap over the 18 parser-touched `headers_t`
instances, the parser error code, and four key parsed fields. The
vendored tree stays pristine (sha256-asserted here against the pin).

The DASH parser's explicit `verify` rejects are preserved: v1model
records them in `standard_metadata.parser_error`, which the wrapper's
egress maps to the err byte (the code table below is the contract with
the example's projection in `src/lib.rs`).

Two symbols the parser references live outside the vendored pair
upstream and are supplied here (each mirrored from the pin, see
third_party/dash/PROVENANCE.md):

- `typedef dash_flow_action_t dash_routing_actions_t;`
  (dash-pipeline/bmv2/dash_metadata.p4 line 9 at the pin)
- `struct metadata_t` — the parser threads `meta` through without
  reading or writing it, so an empty struct is behavior-identical.

Usage: instrument.py <vendored_dash_dir> <out_main.p4>
"""

import hashlib
import sys
from pathlib import Path

# sha256 of the vendored snapshot (sonic-net/DASH @ d5c003dd7774).
# Guards against silent drift between the vendored tree and this
# wrapper's assumptions; update both together when moving the pin.
PINNED_SHA256 = {
    "dash_parser.p4": "2a761e0909a93aa4edcea9849413b57c17f06a6bec2f987f2fdb80abc3d97015",
    "dash_headers.p4": "b3a6030b271d14ae21913413bed7c2227d350053a70356a25e1f5fe981c6fa66",
}

# Bit position per parser-touched headers_t instance, in headers_t
# declaration order. This is the contract with the example's
# projection (src/lib.rs) — keep the two tables identical.
INSTANCE_BITS = [
    "packet_meta",
    "flow_key",
    "flow_data",
    "flow_overlay_data",
    "flow_u0_encap_data",
    "flow_u1_encap_data",
    "u0_ethernet",
    "u0_ipv4",
    "u0_ipv4options",
    "u0_ipv6",
    "u0_udp",
    "u0_tcp",
    "u0_vxlan",
    "customer_ethernet",
    "customer_ipv4",
    "customer_ipv6",
    "customer_udp",
    "customer_tcp",
]

# Parser-error byte (the contract with src/lib.rs). PacketTooShort is
# core.p4's truncation error; the other three are dash_parser.p4's own
# `error {...}` declarations, raised by its verify() calls.
ERROR_CODES = [
    ("error.NoError", 0),
    ("error.PacketTooShort", 1),
    ("error.IPv4IncorrectVersion", 2),
    ("error.IPv4OptionsNotSupported", 3),
    ("error.InvalidIPv4Header", 4),
]


def main() -> None:
    vendored_dir, out_path = Path(sys.argv[1]), Path(sys.argv[2])
    for name, want in PINNED_SHA256.items():
        got = hashlib.sha256((vendored_dir / name).read_bytes()).hexdigest()
        print(f"vendored {name} sha256={got}", file=sys.stderr)
        assert got == want, f"{name} drifted from the pinned snapshot"

    validity = "\n".join(
        f"    if (hd.d.{inst}.isValid()) {{ bm = bm | (32w1 << {bit}); }}"
        for bit, inst in enumerate(INSTANCE_BITS)
    )
    errs = "\n    else ".join(
        f"if (standard_metadata.parser_error == {err}) {{ hd.verdict.err = {code}; }}"
        for err, code in ERROR_CODES
    )

    out_path.write_text(f"""\
// GENERATED by instrument.py — the pakeles observation wrapper for the
// vendored DASH BMv2 parser (capture-time only; never committed).
#define TARGET_BMV2_V1MODEL
#include <core.p4>
#include <v1model.p4>

#include "dash_headers.p4"

// Mirrors dash-pipeline/bmv2/dash_metadata.p4 line 9 at the pin:
typedef dash_flow_action_t dash_routing_actions_t;

// dash_parser threads `meta` through without reading or writing it.
struct metadata_t {{
}}

#include "dash_parser.p4"

// ---- pakeles observation instrumentation ----
// Validity bitmap bit order = headers_t declaration order over the 18
// parser-touched instances (see INSTANCE_BITS in instrument.py); the
// err byte follows ERROR_CODES. Both are the contract with the
// example's projection (src/lib.rs).
header pk_verdict_t {{
  bit<32> bitmap;
  bit<8>  err;
  bit<8>  subtype;
  bit<8>  u0_ihl;
  bit<16> u0_udp_dst;
  bit<16> customer_ether_type;
}}

struct pk_headers_t {{
  headers_t d;
  pk_verdict_t verdict;
}}

parser pk_parser(packet_in packet,
                 out pk_headers_t hd,
                 inout metadata_t meta,
                 inout standard_metadata_t standard_meta) {{
  dash_parser() sub;
  state start {{
    sub.apply(packet, hd.d, meta, standard_meta);
    transition accept;
  }}
}}

control pk_verify(inout pk_headers_t hd, inout metadata_t meta) {{
  apply {{}}
}}

control pk_ingress(inout pk_headers_t hd,
                   inout metadata_t meta,
                   inout standard_metadata_t standard_metadata) {{
  apply {{ standard_metadata.egress_spec = 9w1; }}
}}

control pk_egress(inout pk_headers_t hd,
                  inout metadata_t meta,
                  inout standard_metadata_t standard_metadata) {{
  apply {{
    bit<32> bm = 0;
{validity}
    hd.verdict.setValid();
    hd.verdict.bitmap = bm;
    // `error` cannot be cast to bit<8>; enumerate the codes we map.
    hd.verdict.err = 255;
    {errs}
    hd.verdict.subtype = 0;
    hd.verdict.u0_ihl = 0;
    hd.verdict.u0_udp_dst = 0;
    hd.verdict.customer_ether_type = 0;
    if (hd.d.packet_meta.isValid()) {{
      hd.verdict.subtype = (bit<8>)(bit<4>)hd.d.packet_meta.packet_subtype;
    }}
    if (hd.d.u0_ipv4.isValid()) {{
      hd.verdict.u0_ihl = (bit<8>)hd.d.u0_ipv4.ihl;
    }}
    if (hd.d.u0_udp.isValid()) {{
      hd.verdict.u0_udp_dst = hd.d.u0_udp.dst_port;
    }}
    if (hd.d.customer_ethernet.isValid()) {{
      hd.verdict.customer_ether_type = hd.d.customer_ethernet.ether_type;
    }}
  }}
}}

control pk_compute(inout pk_headers_t hd, inout metadata_t meta) {{
  apply {{}}
}}

control pk_deparser(packet_out packet, in pk_headers_t hd) {{
  apply {{ packet.emit(hd.verdict); }}
}}

V1Switch(pk_parser(), pk_verify(), pk_ingress(), pk_egress(),
         pk_compute(), pk_deparser()) main;
// ---- end pakeles instrumentation ----
""")
    print(f"wrote {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
