//! Direct-translation Wireshark dissector generator (Lua 5.2).
//!
//! Each IR state becomes a readable Lua function with a runtime bit
//! cursor; diagnose-mode behavior (partial tree + expert info +
//! payload rendering) is compiled in. Deliberately rehearses the
//! slice-4 C emitter's shape.
//!
//! Loud caps (generation errors, never silent): referenced fields and
//! masked select keys wider than 32 bits (Lua 5.2 bit32 limit),
//! constants above 2^53 (Lua number exactness), variable-length fields
//! at non-byte-aligned offsets, states with alignment-conflicting
//! entries needing typed ProtoFields.

use crate::ir::pb;
use anyhow::{bail, Result};
use std::collections::{HashMap, HashSet};
use std::fmt::Write;

pub fn generate_lua(ir: &pb::Ir) -> Result<String> {
    let parser = ir
        .parser
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("ir has no parser"))?;
    let proto = format!("pakeles_{}", parser.name);
    let header_types: HashMap<&str, &pb::HeaderType> = parser
        .header_types
        .iter()
        .map(|h| (h.name.as_str(), h))
        .collect();

    let referenced = referenced_fields(parser);
    let entry_align = crate::codegen::entry_alignments(parser);
    let has_meta = !parser.metadata.is_empty();

    let mut out = String::new();
    let w = &mut out;
    writeln!(
        w,
        "-- Generated by pakeles from `{}` (ir {}).",
        parser.name, ir.ir_version
    )?;
    writeln!(w, "-- Do not edit: regenerate with `pakeles gen lua`.")?;
    writeln!(
        w,
        "-- Requires Lua 5.2 (bit32); length arithmetic is signed —"
    )?;
    writeln!(
        w,
        "-- negative computed lengths are treated as out of bounds,"
    )?;
    writeln!(w, "-- matching the reference interpreter's outcome.")?;
    writeln!(
        w,
        "local p = Proto(\"{proto}\", \"Pakeles {}\")",
        parser.name
    )?;
    writeln!(w)?;
    writeln!(
        w,
        "local ef_error = ProtoExpert.new(\"{proto}.malformed\", \"Malformed\", expert.group.MALFORMED, expert.severity.ERROR)"
    )?;
    writeln!(
        w,
        "local ef_info = ProtoExpert.new(\"{proto}.boundary\", \"Payload boundary\", expert.group.PROTOCOL, expert.severity.NOTE)"
    )?;
    writeln!(w, "p.experts = {{ ef_error, ef_info }}")?;
    writeln!(w)?;

    // ProtoField declarations per (instance, field). Each header
    // instance also gets an FT_NONE subtree field: unique JSON keys
    // (text-only subtrees all render as "_ws.lua.text" and collide).
    let mut pf_names: Vec<String> = Vec::new();
    let mut pf_decl = String::from("local pf = {}\n");
    for state in &parser.states {
        for ex in &state.extracts {
            let ht = header_types[ex.header_type.as_str()];
            let inst = instance_name(ex);
            let hdr_var = format!("pf.f_hdr_{inst}");
            if !pf_names.contains(&hdr_var) {
                pf_decl.push_str(&format!(
                    "{hdr_var} = ProtoField.none(\"{proto}.{inst}\", \"{inst}\")\n"
                ));
                pf_names.push(hdr_var);
            }
            for field in &ht.fields {
                let var = pf_var(inst, &field.name);
                if pf_names.contains(&var) {
                    continue; // same instance extracted in several states
                }
                let abbr = format!("{proto}.{inst}.{}", field.name);
                let display = field.display.clone().unwrap_or_default();
                let name = if display.name.is_empty() {
                    field.name.clone()
                } else {
                    display.name.clone()
                };
                let aligned =
                    crate::codegen::field_alignment(parser, &entry_align, state, inst, &field.name)
                        == Some(0);
                let decl = protofield_decl(&abbr, &name, field, &display, aligned)?;
                pf_decl.push_str(&format!("{var} = {decl}\n"));
                pf_names.push(var);
            }
        }
    }
    for md in &parser.metadata {
        let var = format!("pf.f_meta_{}", md.name);
        let abbr = format!("{proto}.meta.{}", md.name);
        let display = md.display.clone().unwrap_or_default();
        let name = if display.name.is_empty() {
            md.name.clone()
        } else {
            display.name.clone()
        };
        pf_decl.push_str(&format!(
            "{var} = ProtoField.uint64(\"{abbr}\", \"{name}\")\n"
        ));
        pf_names.push(var);
    }
    let payload_pf = "pf.f_payload".to_string();
    pf_decl.push_str(&format!(
        "{payload_pf} = ProtoField.bytes(\"{proto}.payload\", \"Payload\")\n"
    ));
    pf_names.push(payload_pf);
    w.push_str(&pf_decl);
    writeln!(w, "p.fields = {{ {} }}", pf_names.join(", "))?;
    writeln!(w)?;
    writeln!(w, "local states = {{}}")?;
    writeln!(w)?;
    // Parsed-value variables shared across state functions: a select key
    // or length expression may reference a field extracted in an EARLIER
    // state (e.g. the GRE flag bits sizing gre_opt.body), so these live
    // in one chunk-scope table (`v`, not one local each — the 200-local
    // chunk limit again) visible to every state function. Re-extraction
    // of a cyclic instance overwrites — last extraction wins, matching
    // the reference interpreter's environment.
    if !referenced.is_empty() {
        writeln!(w, "local v = {{}}")?;
        writeln!(w)?;
    }
    writeln!(w, "local function add_payload(buf, tree, off)")?;
    writeln!(w, "  if off < buf:len() * 8 then")?;
    writeln!(w, "    tree:add(pf.f_payload, buf(math.floor(off / 8)))")?;
    writeln!(w, "  end")?;
    writeln!(w, "end")?;
    writeln!(w)?;

    for state in &parser.states {
        emit_state(w, parser, &header_types, &referenced, &entry_align, state)?;
    }

    writeln!(w, "function p.dissector(buf, pinfo, tree)")?;
    writeln!(w, "  local root = tree:add(p, buf())")?;
    let regions_arg = if super::has_region_ops(parser) {
        ", {}"
    } else {
        ""
    };
    if has_meta {
        let inits: Vec<String> = parser
            .metadata
            .iter()
            .map(|md| format!("{} = {}", md.name, md.init))
            .collect();
        writeln!(w, "  local meta = {{ {} }}", inits.join(", "))?;
        writeln!(
            w,
            "  states.{}(buf, pinfo, root, 0, 0, meta{regions_arg})",
            parser.start_state
        )?;
    } else {
        writeln!(
            w,
            "  states.{}(buf, pinfo, root, 0, 0{regions_arg})",
            parser.start_state
        )?;
    }
    writeln!(w, "end")?;
    writeln!(w)?;
    writeln!(
        w,
        "-- Postdissector: runs on every frame after built-in dissection,"
    )?;
    writeln!(
        w,
        "-- so our tree appears alongside Wireshark's own — side-by-side"
    )?;
    writeln!(
        w,
        "-- comparison for free, no dissector-table precedence fights."
    )?;
    writeln!(w, "register_postdissector(p)")?;
    Ok(out)
}

/// The display/instance name of an extract (defaults to its header
/// type). Public for the conformance harness (pakeles-testkit).
pub fn instance_name(ex: &pb::Extract) -> &str {
    if ex.instance.is_empty() {
        &ex.header_type
    } else {
        &ex.instance
    }
}

// ProtoFields and shared parsed-value variables live in two chunk-level
// tables (`pf`, `v`) rather than one `local` each: Lua caps locals at
// 200 per function, and a switch.p4-sized parser needs 360 ProtoFields.
fn pf_var(inst: &str, field: &str) -> String {
    format!("pf.f_{inst}_{field}")
}

fn val_var(inst: &str, field: &str) -> String {
    format!("v.v_{inst}_{field}")
}

/// (instance, field) pairs referenced by any expression in the parser.
fn referenced_fields(parser: &pb::Parser) -> HashSet<(String, String)> {
    let mut out = HashSet::new();
    let mut walk = |e: &pb::Expr| collect_refs(e, &mut out);
    for ht in &parser.header_types {
        for f in &ht.fields {
            if let Some(pb::field_width::Width::ByteLen(e)) =
                f.width.as_ref().and_then(|w| w.width.as_ref())
            {
                walk(e);
            }
        }
    }
    for s in &parser.states {
        if let Some(pb::transition::Kind::Select(sel)) =
            s.transition.as_ref().and_then(|t| t.kind.as_ref())
        {
            for k in &sel.keys {
                walk(k);
            }
        }
        for a in &s.assigns {
            if let Some(v) = &a.value {
                walk(v);
            }
        }
        for op in &s.region_ops {
            if let Some(pb::region_op::Kind::Push(e)) = &op.kind {
                walk(e);
            }
        }
    }
    out
}

fn collect_refs(e: &pb::Expr, out: &mut HashSet<(String, String)>) {
    match &e.kind {
        Some(pb::expr::Kind::Field(r)) => {
            out.insert((r.header.clone(), r.field.clone()));
        }
        Some(pb::expr::Kind::Bin(b)) => {
            if let Some(l) = &b.lhs {
                collect_refs(l, out);
            }
            if let Some(r) = &b.rhs {
                collect_refs(r, out);
            }
        }
        Some(pb::expr::Kind::Metadata(_)) => {}
        _ => {}
    }
}

fn protofield_decl(
    abbr: &str,
    name: &str,
    field: &pb::Field,
    display: &pb::Display,
    byte_aligned: bool,
) -> Result<String> {
    let format = pb::DisplayFormat::try_from(display.format).unwrap_or_default();
    let width = match field.width.as_ref().and_then(|w| w.width.as_ref()) {
        Some(pb::field_width::Width::Bits(n)) => Some(*n),
        _ => None,
    };
    if let Some(width) = width {
        match format {
            pb::DisplayFormat::Ether if width == 48 && byte_aligned => {
                return Ok(format!("ProtoField.ether(\"{abbr}\", \"{name}\")"));
            }
            pb::DisplayFormat::Ipv4 if width == 32 && byte_aligned => {
                return Ok(format!("ProtoField.ipv4(\"{abbr}\", \"{name}\")"));
            }
            _ => {}
        }
        let ctor = match width {
            1..=8 => "uint8",
            9..=16 => "uint16",
            17..=24 => "uint24",
            25..=32 => "uint32",
            _ => "uint64",
        };
        let base = match format {
            pb::DisplayFormat::Dec => "base.DEC",
            // base.BIN doesn't exist for integers; HEX is the closest.
            _ => "base.HEX",
        };
        let labels = if display.value_labels.is_empty() {
            String::new()
        } else {
            let entries: Vec<String> = display
                .value_labels
                .iter()
                .map(|vl| format!("[{}] = \"{}\"", vl.value, vl.label))
                .collect();
            format!(", {{ {} }}", entries.join(", "))
        };
        Ok(format!(
            "ProtoField.{ctor}(\"{abbr}\", \"{name}\", {base}{labels})"
        ))
    } else {
        Ok(format!("ProtoField.bytes(\"{abbr}\", \"{name}\")"))
    }
}

fn expr_lua(e: &pb::Expr, referenced: &HashSet<(String, String)>) -> Result<String> {
    match e.kind.as_ref() {
        // Structural bytes to the innermost region end; only legal
        // with a region open (validator), so regions[#regions] exists.
        Some(pb::expr::Kind::Remaining(_)) => {
            Ok("math.floor((regions[#regions] - off) / 8)".to_string())
        }
        Some(pb::expr::Kind::Constant(v)) => {
            if *v > (1u64 << 53) {
                bail!("constant {v} exceeds Lua number exactness (2^53)");
            }
            Ok(format!("{v}"))
        }
        Some(pb::expr::Kind::Field(r)) => {
            debug_assert!(referenced.contains(&(r.header.clone(), r.field.clone())));
            Ok(val_var(&r.header, &r.field))
        }
        Some(pb::expr::Kind::Bin(b)) => {
            let l = expr_lua(b.lhs.as_deref().unwrap(), referenced)?;
            let r = expr_lua(b.rhs.as_deref().unwrap(), referenced)?;
            let op = pb::BinOpKind::try_from(b.op).unwrap_or_default();
            Ok(match op {
                pb::BinOpKind::Add => format!("({l} + {r})"),
                pb::BinOpKind::Sub => format!("({l} - {r})"),
                pb::BinOpKind::Mul => format!("({l} * {r})"),
                pb::BinOpKind::Shl => format!("({l} * 2 ^ {r})"),
                pb::BinOpKind::Shr => format!("math.floor({l} / 2 ^ {r})"),
                pb::BinOpKind::And => format!("bit32.band({l}, {r})"),
                pb::BinOpKind::Or => format!("bit32.bor({l}, {r})"),
                pb::BinOpKind::Unspecified => bail!("unspecified binop"),
            })
        }
        Some(pb::expr::Kind::Metadata(r)) => Ok(format!("meta.{}", r.name)),
        None => bail!("empty expression"),
    }
}

fn entry_lua(entry: &pb::KeysetEntry, key_lua: &str, key_width: Option<u32>) -> Result<String> {
    match entry.kind.as_ref() {
        Some(pb::keyset_entry::Kind::Value(v)) => Ok(format!("{key_lua} == {v}")),
        Some(pb::keyset_entry::Kind::Masked(m)) => {
            if key_width.is_none_or(|w| w > 32) {
                bail!("masked select keys wider than 32 bits are not supported by the Lua backend yet");
            }
            Ok(format!(
                "bit32.band({key_lua}, {}) == {}",
                m.mask,
                m.value & m.mask
            ))
        }
        Some(pb::keyset_entry::Kind::Range(r)) => {
            Ok(format!("({key_lua} >= {} and {key_lua} <= {})", r.lo, r.hi))
        }
        None => Ok("false".into()),
    }
}

fn target_lua(
    parser: &pb::Parser,
    target: &pb::Target,
    indent: &str,
    w: &mut String,
) -> Result<()> {
    let has_meta = !parser.metadata.is_empty();
    match target.kind.as_ref() {
        Some(pb::target::Kind::State(name)) => {
            let meta_arg = if has_meta { ", meta" } else { "" };
            let regions_arg = if super::has_region_ops(parser) {
                ", regions"
            } else {
                ""
            };
            writeln!(
                w,
                "{indent}return states.{name}(buf, pinfo, tree, off, depth{meta_arg}{regions_arg})"
            )?;
        }
        Some(pb::target::Kind::Accept(_)) => {
            if has_meta {
                for md in &parser.metadata {
                    // Wireshark's Lua binding requires a userdata Int64/
                    // UInt64 for FT_UINT64 `add`; a bare Lua number
                    // throws "bad self (userdata expected, got number)"
                    // and aborts the rest of the accept branch (only one
                    // Lua error fires per packet), silently dropping
                    // add_payload below.
                    writeln!(
                        w,
                        "{indent}tree:add(pf.f_meta_{}, UInt64(meta.{}))",
                        md.name, md.name
                    )?;
                }
            }
            writeln!(w, "{indent}add_payload(buf, tree, off)")?;
            writeln!(w, "{indent}return off")?;
        }
        Some(pb::target::Kind::Reject(r)) => {
            let info = r.annotations.get("severity").map(String::as_str) == Some("info");
            if info {
                writeln!(w, "{indent}add_payload(buf, tree, off)")?;
                writeln!(
                    w,
                    "{indent}tree:add_proto_expert_info(ef_info, \"{}\")",
                    r.reason
                )?;
            } else {
                writeln!(
                    w,
                    "{indent}tree:add_proto_expert_info(ef_error, \"{}\")",
                    r.reason
                )?;
            }
            writeln!(w, "{indent}return off")?;
        }
        None => bail!("empty target"),
    }
    Ok(())
}

fn emit_state(
    w: &mut String,
    parser: &pb::Parser,
    header_types: &HashMap<&str, &pb::HeaderType>,
    referenced: &HashSet<(String, String)>,
    entry_align: &HashMap<String, Option<u32>>,
    state: &pb::State,
) -> Result<()> {
    let has_meta = !parser.metadata.is_empty();
    let meta_param = if has_meta { ", meta" } else { "" };
    let has_regions = crate::codegen::has_region_ops(parser);
    let regions_param = if has_regions { ", regions" } else { "" };
    writeln!(
        w,
        "function states.{}(buf, pinfo, tree, off, depth{meta_param}{regions_param})",
        state.name
    )?;
    writeln!(w, "  depth = depth + 1")?;
    writeln!(w, "  if depth > {} then", parser.max_depth)?;
    writeln!(
        w,
        "    tree:add_proto_expert_info(ef_error, \"max depth exceeded\")"
    )?;
    writeln!(w, "    return off")?;
    writeln!(w, "  end")?;
    writeln!(w, "  local avail = buf:len() * 8")?;

    for ex in &state.extracts {
        let ht = header_types[ex.header_type.as_str()];
        let inst = instance_name(ex);
        // FT_NONE subtree under the single proto root: unique JSON key
        // per header instance.
        writeln!(
            w,
            "  local hdr_{inst} = tree:add(pf.f_hdr_{inst}, buf(math.floor(off / 8)))"
        )?;
        for field in &ht.fields {
            let pf = pf_var(inst, &field.name);
            match field.width.as_ref().and_then(|x| x.width.as_ref()) {
                Some(pb::field_width::Width::Bits(n)) => {
                    let n = *n;
                    if has_regions {
                        // Region end first (avail-free reason rule).
                        writeln!(
                            w,
                            "  if regions[#regions] and off + {n} > regions[#regions] then"
                        )?;
                        writeln!(
                            w,
                            "    hdr_{inst}:add_proto_expert_info(ef_error, \"out of region bounds in {inst}.{}\")",
                            field.name
                        )?;
                        writeln!(w, "    return off")?;
                        writeln!(w, "  end")?;
                    }
                    writeln!(w, "  if off + {n} > avail then")?;
                    writeln!(
                        w,
                        "    hdr_{inst}:add_proto_expert_info(ef_error, \"out of bounds in {inst}.{}\")",
                        field.name
                    )?;
                    writeln!(w, "    return off")?;
                    writeln!(w, "  end")?;
                    let cover =
                        format!("buf(math.floor(off / 8), math.floor((off % 8 + {n} + 7) / 8))");
                    let is_ref = referenced.contains(&(inst.to_string(), field.name.clone()));
                    if is_ref && n > 32 {
                        bail!(
                            "referenced field `{inst}.{}` wider than 32 bits is not supported by the Lua backend yet",
                            field.name
                        );
                    }
                    let aligned = crate::codegen::field_alignment(
                        parser,
                        entry_align,
                        state,
                        inst,
                        &field.name,
                    ) == Some(0);
                    let format = field
                        .display
                        .as_ref()
                        .and_then(|d| pb::DisplayFormat::try_from(d.format).ok())
                        .unwrap_or_default();
                    let typed_range_add = aligned
                        && ((format == pb::DisplayFormat::Ether && n == 48)
                            || (format == pb::DisplayFormat::Ipv4 && n == 32)
                            || n > 32);
                    if is_ref {
                        let v = val_var(inst, &field.name);
                        writeln!(w, "  {v} = buf():bitfield(off, {n})")?;
                        writeln!(w, "  hdr_{inst}:add({pf}, {cover}, {v})")?;
                    } else if typed_range_add {
                        // Byte-aligned: exact range, Wireshark decodes.
                        writeln!(
                            w,
                            "  hdr_{inst}:add({pf}, buf(math.floor(off / 8), {}))",
                            n.div_ceil(8)
                        )?;
                    } else {
                        writeln!(
                            w,
                            "  hdr_{inst}:add({pf}, {cover}, buf():bitfield(off, {n}))"
                        )?;
                    }
                    writeln!(w, "  off = off + {n}")?;
                }
                Some(pb::field_width::Width::ByteLen(expr)) => {
                    let aligned = crate::codegen::field_alignment(
                        parser,
                        entry_align,
                        state,
                        inst,
                        &field.name,
                    ) == Some(0);
                    if !aligned {
                        bail!(
                            "variable-length field `{inst}.{}` is not statically byte-aligned",
                            field.name
                        );
                    }
                    let len = format!("len_{inst}_{}", field.name);
                    writeln!(w, "  local {len} = {}", expr_lua(expr, referenced)?)?;
                    if has_regions {
                        writeln!(
                            w,
                            "  if regions[#regions] and ({len} < 0 or off + {len} * 8 > regions[#regions]) then"
                        )?;
                        writeln!(
                            w,
                            "    hdr_{inst}:add_proto_expert_info(ef_error, \"out of region bounds in {inst}.{}\")",
                            field.name
                        )?;
                        writeln!(w, "    return off")?;
                        writeln!(w, "  end")?;
                    }
                    writeln!(w, "  if {len} < 0 or off + {len} * 8 > avail then")?;
                    writeln!(
                        w,
                        "    hdr_{inst}:add_proto_expert_info(ef_error, \"out of bounds in {inst}.{}\")",
                        field.name
                    )?;
                    writeln!(w, "    return off")?;
                    writeln!(w, "  end")?;
                    writeln!(w, "  if {len} > 0 then")?;
                    writeln!(
                        w,
                        "    hdr_{inst}:add({pf}, buf(math.floor(off / 8), {len}))"
                    )?;
                    writeln!(w, "  end")?;
                    writeln!(w, "  off = off + {len} * 8")?;
                }
                None => bail!("field `{}` has no width", field.name),
            }
        }
    }

    for a in &state.assigns {
        let bits = parser
            .metadata
            .iter()
            .find(|m| m.name == a.metadata)
            .map(|m| m.bits)
            .ok_or_else(|| anyhow::anyhow!("assign to undeclared metadata `{}`", a.metadata))?;
        let rhs = expr_lua(
            a.value
                .as_ref()
                .ok_or_else(|| anyhow::anyhow!("assign without value"))?,
            referenced,
        )?;
        if bits <= 53 {
            writeln!(w, "  meta.{} = ({}) % 2^{}", a.metadata, rhs, bits)?;
        } else {
            writeln!(
                w,
                "  meta.{} = ({}) -- wrap elided: >53-bit metadata exceeds Lua number precision",
                a.metadata, rhs
            )?;
        }
    }

    for op in &state.region_ops {
        match op.kind.as_ref() {
            Some(pb::region_op::Kind::Push(e)) => {
                writeln!(w, "  do")?;
                writeln!(w, "    local rlen = {}", expr_lua(e, referenced)?)?;
                writeln!(
                    w,
                    "    if rlen < 0 or (regions[#regions] and off + rlen * 8 > regions[#regions]) then"
                )?;
                writeln!(
                    w,
                    "      tree:add_proto_expert_info(ef_error, \"region out of bounds\")"
                )?;
                writeln!(w, "      return off")?;
                writeln!(w, "    end")?;
                writeln!(w, "    regions[#regions + 1] = off + rlen * 8")?;
                writeln!(w, "  end")?;
            }
            Some(pb::region_op::Kind::Pop(_)) => {
                writeln!(w, "  do")?;
                writeln!(w, "    local rend = table.remove(regions)")?;
                writeln!(w, "    if off < rend then")?;
                writeln!(
                    w,
                    "      tree:add_proto_expert_info(ef_error, \"region not exhausted\")"
                )?;
                writeln!(w, "      return off")?;
                writeln!(w, "    end")?;
                writeln!(w, "  end")?;
            }
            None => bail!("empty region op"),
        }
    }

    match state.transition.as_ref().and_then(|t| t.kind.as_ref()) {
        None => bail!("state `{}` has no transition", state.name),
        Some(pb::transition::Kind::Direct(t)) => {
            target_lua(parser, t, "  ", w)?;
        }
        Some(pb::transition::Kind::Select(sel)) => {
            let keys: Vec<String> = sel
                .keys
                .iter()
                .map(|k| expr_lua(k, referenced))
                .collect::<Result<_>>()?;
            let key_widths: Vec<Option<u32>> =
                sel.keys.iter().map(|k| key_bit_width(parser, k)).collect();
            for (i, arm) in sel.arms.iter().enumerate() {
                let conds: Vec<String> = arm
                    .entries
                    .iter()
                    .zip(keys.iter().zip(&key_widths))
                    .map(|(e, (k, wd))| entry_lua(e, k, *wd))
                    .collect::<Result<_>>()?;
                let kw = if i == 0 { "if" } else { "elseif" };
                writeln!(w, "  {kw} {} then", conds.join(" and "))?;
                target_lua(
                    parser,
                    arm.next
                        .as_ref()
                        .ok_or_else(|| anyhow::anyhow!("arm without target"))?,
                    "    ",
                    w,
                )?;
            }
            if sel.arms.is_empty() {
                match sel.default_target.as_ref() {
                    Some(t) => target_lua(parser, t, "  ", w)?,
                    None => {
                        writeln!(
                            w,
                            "  tree:add_proto_expert_info(ef_error, \"no matching select arm\")"
                        )?;
                        writeln!(w, "  return off")?;
                    }
                }
            } else {
                writeln!(w, "  else")?;
                match sel.default_target.as_ref() {
                    Some(t) => target_lua(parser, t, "    ", w)?,
                    None => {
                        writeln!(
                            w,
                            "    tree:add_proto_expert_info(ef_error, \"no matching select arm\")"
                        )?;
                        writeln!(w, "    return off")?;
                    }
                }
                writeln!(w, "  end")?;
            }
        }
    }
    writeln!(w, "end")?;
    writeln!(w)?;
    Ok(())
}

/// Bit width of a select key when it is a plain field ref.
fn key_bit_width(parser: &pb::Parser, key: &pb::Expr) -> Option<u32> {
    if let Some(pb::expr::Kind::Metadata(r)) = &key.kind {
        return parser
            .metadata
            .iter()
            .find(|m| m.name == r.name)
            .map(|m| m.bits);
    }
    if let Some(pb::expr::Kind::Field(r)) = &key.kind {
        for s in &parser.states {
            for ex in &s.extracts {
                if instance_name(ex) == r.header {
                    let ht = parser
                        .header_types
                        .iter()
                        .find(|h| h.name == ex.header_type)?;
                    let f = ht.fields.iter().find(|f| f.name == r.field)?;
                    if let Some(pb::field_width::Width::Bits(b)) =
                        f.width.as_ref().and_then(|x| x.width.as_ref())
                    {
                        return Some(*b);
                    }
                }
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fixtures::eth_ipvx_l4;

    #[test]
    fn metadata_lua_emission() {
        let ir = crate::builder::meta_loop(); // shared test IR from Task 2
        let lua = generate_lua(&ir).unwrap();
        assert!(lua.contains("pf.f_meta_acc"));
        assert!(lua.contains("local meta = { flag = 0, acc = 0 }"));
        assert!(lua.contains("meta.acc = "));
        // FT_UINT64 `add` needs a userdata Int64/UInt64, not a bare Lua
        // number — see the comment in target_lua's Accept arm.
        assert!(lua.contains("tree:add(pf.f_meta_acc, UInt64(meta.acc))"));
        assert!(lua.contains("tree:add(pf.f_meta_flag, UInt64(meta.flag))"));
        let plain = generate_lua(&crate::fixtures::eth_ipvx_l4()).unwrap();
        assert!(!plain.contains("meta"));
    }

    // The committed-dissector equality guards live with each example
    // (tests/synthetic_gallery.rs and the example crates); this checks
    // the generated shape.
    #[test]
    fn dissector_has_states_and_protofields() {
        let lua = generate_lua(&eth_ipvx_l4()).unwrap();
        assert!(lua.contains("function states.parse_ipv4"));
        assert!(lua.contains("ProtoField.ether"));
        assert!(lua.contains("[6] = \"TCP\""));
    }

    #[test]
    fn wide_masked_key_is_generation_error() {
        use crate::builder::*;
        let ir = ParserBuilder::new("wide", 2)
            .header(HeaderTypeBuilder::new("h").bits("f", 48))
            .state(StateBuilder::new("a").extract("h").select(
                vec![f("h", "f")],
                vec![arm(vec![masked(0, 0xFF)], to("b"))],
                reject("no"),
            ))
            .state(StateBuilder::new("b").accept())
            .start("a")
            .build()
            .unwrap();
        let err = generate_lua(&ir).unwrap_err();
        assert!(err.to_string().contains("wider than 32 bits"));
    }

    #[test]
    fn masked_select_on_metadata_key_emits_band() {
        use crate::builder::*;
        let ir = ParserBuilder::new("meta_masked", 2)
            .meta("tag", 8, 0)
            .state(StateBuilder::new("a").select(
                vec![m("tag")],
                vec![arm(vec![masked(0x02, 0x0F)], to("b"))],
                reject("no"),
            ))
            .state(StateBuilder::new("b").accept())
            .start("a")
            .build()
            .unwrap();
        let lua = generate_lua(&ir).unwrap();
        assert!(lua.contains("bit32.band(meta.tag, 15) == 2"));
    }

    #[test]
    fn masked_select_on_wide_metadata_key_is_generation_error() {
        use crate::builder::*;
        let ir = ParserBuilder::new("meta_masked_wide", 2)
            .meta("tag", 40, 0)
            .state(StateBuilder::new("a").select(
                vec![m("tag")],
                vec![arm(vec![masked(0, 0xFF)], to("b"))],
                reject("no"),
            ))
            .state(StateBuilder::new("b").accept())
            .start("a")
            .build()
            .unwrap();
        let err = generate_lua(&ir).unwrap_err();
        assert!(err.to_string().contains("wider than 32 bits"));
    }
}
